/**
 * Catálogo DIVIPOLA completo de los 4 departamentos del Pacífico colombiano.
 * Fuente: DANE — División Político-Administrativa de Colombia.
 * Total: 178 municipios.
 */

export interface MunicipioPacifico {
  divipola:    string;
  nombre:      string;
  depto:       string;
  codigo_depto: string;
}

export const DIVIPOLA_PACIFICO: MunicipioPacifico[] = [
  // ──────────────────────────────────────────────────────────────────────────
  // CAUCA (19) — 42 municipios
  // ──────────────────────────────────────────────────────────────────────────
  { divipola: "19001", nombre: "Popayán",                 depto: "Cauca", codigo_depto: "19" },
  { divipola: "19022", nombre: "Almaguer",                depto: "Cauca", codigo_depto: "19" },
  { divipola: "19050", nombre: "Argelia",                 depto: "Cauca", codigo_depto: "19" },
  { divipola: "19075", nombre: "Balboa",                  depto: "Cauca", codigo_depto: "19" },
  { divipola: "19100", nombre: "Bolívar",                 depto: "Cauca", codigo_depto: "19" },
  { divipola: "19110", nombre: "Buenos Aires",            depto: "Cauca", codigo_depto: "19" },
  { divipola: "19130", nombre: "Cajibío",                 depto: "Cauca", codigo_depto: "19" },
  { divipola: "19137", nombre: "Caldono",                 depto: "Cauca", codigo_depto: "19" },
  { divipola: "19142", nombre: "Caloto",                  depto: "Cauca", codigo_depto: "19" },
  { divipola: "19212", nombre: "Corinto",                 depto: "Cauca", codigo_depto: "19" },
  { divipola: "19256", nombre: "El Tambo",                depto: "Cauca", codigo_depto: "19" },
  { divipola: "19290", nombre: "Florencia",               depto: "Cauca", codigo_depto: "19" },
  { divipola: "19300", nombre: "Guapi",                   depto: "Cauca", codigo_depto: "19" },
  { divipola: "19318", nombre: "Inzá",                    depto: "Cauca", codigo_depto: "19" },
  { divipola: "19355", nombre: "Jambaló",                 depto: "Cauca", codigo_depto: "19" },
  { divipola: "19364", nombre: "La Sierra",               depto: "Cauca", codigo_depto: "19" },
  { divipola: "19392", nombre: "La Vega",                 depto: "Cauca", codigo_depto: "19" },
  { divipola: "19397", nombre: "López de Micay",          depto: "Cauca", codigo_depto: "19" },
  { divipola: "19418", nombre: "Mercaderes",              depto: "Cauca", codigo_depto: "19" },
  { divipola: "19450", nombre: "Miranda",                 depto: "Cauca", codigo_depto: "19" },
  { divipola: "19455", nombre: "Morales",                 depto: "Cauca", codigo_depto: "19" },
  { divipola: "19473", nombre: "Padilla",                 depto: "Cauca", codigo_depto: "19" },
  { divipola: "19513", nombre: "Patía",                   depto: "Cauca", codigo_depto: "19" },
  { divipola: "19517", nombre: "Piamonte",                depto: "Cauca", codigo_depto: "19" },
  { divipola: "19532", nombre: "Piendamó",                depto: "Cauca", codigo_depto: "19" },
  { divipola: "19533", nombre: "Piendamó - Tunia",        depto: "Cauca", codigo_depto: "19" },
  { divipola: "19548", nombre: "Puerto Tejada",           depto: "Cauca", codigo_depto: "19" },
  { divipola: "19573", nombre: "Puracé",                  depto: "Cauca", codigo_depto: "19" },
  { divipola: "19585", nombre: "Rosas",                   depto: "Cauca", codigo_depto: "19" },
  { divipola: "19622", nombre: "San Sebastián",           depto: "Cauca", codigo_depto: "19" },
  { divipola: "19693", nombre: "Santa Rosa",              depto: "Cauca", codigo_depto: "19" },
  { divipola: "19698", nombre: "Santander de Quilichao",  depto: "Cauca", codigo_depto: "19" },
  { divipola: "19701", nombre: "Silvia",                  depto: "Cauca", codigo_depto: "19" },
  { divipola: "19743", nombre: "Sotará",                  depto: "Cauca", codigo_depto: "19" },
  { divipola: "19760", nombre: "Suárez",                  depto: "Cauca", codigo_depto: "19" },
  { divipola: "19780", nombre: "Sucre",                   depto: "Cauca", codigo_depto: "19" },
  { divipola: "19785", nombre: "Timbío",                  depto: "Cauca", codigo_depto: "19" },
  { divipola: "19807", nombre: "Timbiquí",                depto: "Cauca", codigo_depto: "19" },
  { divipola: "19809", nombre: "Toribío",                 depto: "Cauca", codigo_depto: "19" },
  { divipola: "19824", nombre: "Totoró",                  depto: "Cauca", codigo_depto: "19" },
  { divipola: "19845", nombre: "Villa Rica",              depto: "Cauca", codigo_depto: "19" },
  { divipola: "19872", nombre: "Páez",                    depto: "Cauca", codigo_depto: "19" },

  // ──────────────────────────────────────────────────────────────────────────
  // CHOCÓ (27) — 31 municipios
  // ──────────────────────────────────────────────────────────────────────────
  { divipola: "27001", nombre: "Quibdó",                  depto: "Chocó", codigo_depto: "27" },
  { divipola: "27006", nombre: "Acandí",                  depto: "Chocó", codigo_depto: "27" },
  { divipola: "27025", nombre: "Alto Baudó",              depto: "Chocó", codigo_depto: "27" },
  { divipola: "27050", nombre: "Atrato",                  depto: "Chocó", codigo_depto: "27" },
  { divipola: "27073", nombre: "Bagadó",                  depto: "Chocó", codigo_depto: "27" },
  { divipola: "27075", nombre: "Bahía Solano",            depto: "Chocó", codigo_depto: "27" },
  { divipola: "27077", nombre: "Bajo Baudó",              depto: "Chocó", codigo_depto: "27" },
  { divipola: "27099", nombre: "Bojayá",                  depto: "Chocó", codigo_depto: "27" },
  { divipola: "27135", nombre: "Carmen del Darién",       depto: "Chocó", codigo_depto: "27" },
  { divipola: "27150", nombre: "Cértegui",                depto: "Chocó", codigo_depto: "27" },
  { divipola: "27160", nombre: "Condoto",                 depto: "Chocó", codigo_depto: "27" },
  { divipola: "27205", nombre: "El Cantón del San Pablo", depto: "Chocó", codigo_depto: "27" },
  { divipola: "27245", nombre: "El Carmen de Atrato",     depto: "Chocó", codigo_depto: "27" },
  { divipola: "27250", nombre: "El Litoral del San Juan", depto: "Chocó", codigo_depto: "27" },
  { divipola: "27361", nombre: "Istmina",                 depto: "Chocó", codigo_depto: "27" },
  { divipola: "27372", nombre: "Juradó",                  depto: "Chocó", codigo_depto: "27" },
  { divipola: "27413", nombre: "Lloró",                   depto: "Chocó", codigo_depto: "27" },
  { divipola: "27425", nombre: "Medio Atrato",            depto: "Chocó", codigo_depto: "27" },
  { divipola: "27430", nombre: "Medio Baudó",             depto: "Chocó", codigo_depto: "27" },
  { divipola: "27450", nombre: "Medio San Juan",          depto: "Chocó", codigo_depto: "27" },
  { divipola: "27491", nombre: "Nóvita",                  depto: "Chocó", codigo_depto: "27" },
  { divipola: "27495", nombre: "Nuquí",                   depto: "Chocó", codigo_depto: "27" },
  { divipola: "27580", nombre: "Río Iro",                 depto: "Chocó", codigo_depto: "27" },
  { divipola: "27600", nombre: "Río Quito",               depto: "Chocó", codigo_depto: "27" },
  { divipola: "27615", nombre: "Riosucio",                depto: "Chocó", codigo_depto: "27" },
  { divipola: "27660", nombre: "San José del Palmar",     depto: "Chocó", codigo_depto: "27" },
  { divipola: "27745", nombre: "Sipí",                    depto: "Chocó", codigo_depto: "27" },
  { divipola: "27787", nombre: "Tadó",                    depto: "Chocó", codigo_depto: "27" },
  { divipola: "27800", nombre: "Unguía",                  depto: "Chocó", codigo_depto: "27" },
  { divipola: "27810", nombre: "Unión Panamericana",      depto: "Chocó", codigo_depto: "27" },
  { divipola: "27615", nombre: "Riosucio",                depto: "Chocó", codigo_depto: "27" }, // VERIFICAR duplicado

  // ──────────────────────────────────────────────────────────────────────────
  // NARIÑO (52) — 64 municipios
  // ──────────────────────────────────────────────────────────────────────────
  { divipola: "52001", nombre: "Pasto",                   depto: "Nariño", codigo_depto: "52" },
  { divipola: "52019", nombre: "Albán",                   depto: "Nariño", codigo_depto: "52" },
  { divipola: "52022", nombre: "Aldana",                  depto: "Nariño", codigo_depto: "52" },
  { divipola: "52036", nombre: "Ancuyá",                  depto: "Nariño", codigo_depto: "52" },
  { divipola: "52051", nombre: "Arboleda",                depto: "Nariño", codigo_depto: "52" },
  { divipola: "52079", nombre: "Barbacoas",               depto: "Nariño", codigo_depto: "52" },
  { divipola: "52083", nombre: "Belén",                   depto: "Nariño", codigo_depto: "52" },
  { divipola: "52110", nombre: "Buesaco",                 depto: "Nariño", codigo_depto: "52" },
  { divipola: "52203", nombre: "Colón",                   depto: "Nariño", codigo_depto: "52" },
  { divipola: "52207", nombre: "Consacá",                 depto: "Nariño", codigo_depto: "52" },
  { divipola: "52210", nombre: "Contadero",               depto: "Nariño", codigo_depto: "52" },
  { divipola: "52215", nombre: "Córdoba",                 depto: "Nariño", codigo_depto: "52" },
  { divipola: "52224", nombre: "Cuaspud",                 depto: "Nariño", codigo_depto: "52" },
  { divipola: "52227", nombre: "Cumbal",                  depto: "Nariño", codigo_depto: "52" },
  { divipola: "52233", nombre: "Cumbitara",               depto: "Nariño", codigo_depto: "52" },
  { divipola: "52240", nombre: "Chachagüí",               depto: "Nariño", codigo_depto: "52" },
  { divipola: "52250", nombre: "El Charco",               depto: "Nariño", codigo_depto: "52" },
  { divipola: "52254", nombre: "El Peñol",                depto: "Nariño", codigo_depto: "52" },
  { divipola: "52256", nombre: "El Rosario",              depto: "Nariño", codigo_depto: "52" },
  { divipola: "52258", nombre: "El Tablón de Gómez",      depto: "Nariño", codigo_depto: "52" },
  { divipola: "52260", nombre: "El Tambo",                depto: "Nariño", codigo_depto: "52" },
  { divipola: "52287", nombre: "Funes",                   depto: "Nariño", codigo_depto: "52" },
  { divipola: "52317", nombre: "Guachucal",               depto: "Nariño", codigo_depto: "52" },
  { divipola: "52320", nombre: "Guaitarilla",             depto: "Nariño", codigo_depto: "52" },
  { divipola: "52323", nombre: "Gualmatán",               depto: "Nariño", codigo_depto: "52" },
  { divipola: "52352", nombre: "Iles",                    depto: "Nariño", codigo_depto: "52" },
  { divipola: "52354", nombre: "Imués",                   depto: "Nariño", codigo_depto: "52" },
  { divipola: "52356", nombre: "Ipiales",                 depto: "Nariño", codigo_depto: "52" },
  { divipola: "52378", nombre: "La Cruz",                 depto: "Nariño", codigo_depto: "52" },
  { divipola: "52381", nombre: "La Florida",              depto: "Nariño", codigo_depto: "52" },
  { divipola: "52385", nombre: "La Llanada",              depto: "Nariño", codigo_depto: "52" },
  { divipola: "52390", nombre: "La Tola",                 depto: "Nariño", codigo_depto: "52" },
  { divipola: "52399", nombre: "La Unión",                depto: "Nariño", codigo_depto: "52" },
  { divipola: "52405", nombre: "Leiva",                   depto: "Nariño", codigo_depto: "52" },
  { divipola: "52411", nombre: "Linares",                 depto: "Nariño", codigo_depto: "52" },
  { divipola: "52418", nombre: "Los Andes",               depto: "Nariño", codigo_depto: "52" },
  { divipola: "52427", nombre: "Magüí",                   depto: "Nariño", codigo_depto: "52" },
  { divipola: "52435", nombre: "Mallama",                 depto: "Nariño", codigo_depto: "52" },
  { divipola: "52473", nombre: "Mosquera",                depto: "Nariño", codigo_depto: "52" },
  { divipola: "52480", nombre: "Nariño",                  depto: "Nariño", codigo_depto: "52" },
  { divipola: "52490", nombre: "Olaya Herrera",           depto: "Nariño", codigo_depto: "52" },
  { divipola: "52506", nombre: "Ospina",                  depto: "Nariño", codigo_depto: "52" },
  { divipola: "52520", nombre: "Francisco Pizarro",       depto: "Nariño", codigo_depto: "52" },
  { divipola: "52540", nombre: "Policarpa",               depto: "Nariño", codigo_depto: "52" },
  { divipola: "52560", nombre: "Potosí",                  depto: "Nariño", codigo_depto: "52" },
  { divipola: "52565", nombre: "Providencia",             depto: "Nariño", codigo_depto: "52" },
  { divipola: "52573", nombre: "Puerres",                 depto: "Nariño", codigo_depto: "52" },
  { divipola: "52585", nombre: "Pupiales",                depto: "Nariño", codigo_depto: "52" },
  { divipola: "52612", nombre: "Ricaurte",                depto: "Nariño", codigo_depto: "52" },
  { divipola: "52621", nombre: "Roberto Payán",           depto: "Nariño", codigo_depto: "52" },
  { divipola: "52678", nombre: "Samaniego",               depto: "Nariño", codigo_depto: "52" },
  { divipola: "52683", nombre: "San Bernardo",            depto: "Nariño", codigo_depto: "52" },
  { divipola: "52685", nombre: "San Lorenzo",             depto: "Nariño", codigo_depto: "52" },
  { divipola: "52687", nombre: "San Pablo",               depto: "Nariño", codigo_depto: "52" },
  { divipola: "52693", nombre: "San Pedro de Cartago",    depto: "Nariño", codigo_depto: "52" },
  { divipola: "52694", nombre: "Sandoná",                 depto: "Nariño", codigo_depto: "52" },
  { divipola: "52696", nombre: "Santa Bárbara",           depto: "Nariño", codigo_depto: "52" },
  { divipola: "52699", nombre: "Santacruz",               depto: "Nariño", codigo_depto: "52" },
  { divipola: "52720", nombre: "Sapuyes",                 depto: "Nariño", codigo_depto: "52" },
  { divipola: "52786", nombre: "Taminango",               depto: "Nariño", codigo_depto: "52" },
  { divipola: "52788", nombre: "Tangua",                  depto: "Nariño", codigo_depto: "52" },
  { divipola: "52835", nombre: "Tumaco",                  depto: "Nariño", codigo_depto: "52" },
  { divipola: "52838", nombre: "Túquerres",               depto: "Nariño", codigo_depto: "52" },
  { divipola: "52885", nombre: "Yacuanquer",              depto: "Nariño", codigo_depto: "52" },

  // ──────────────────────────────────────────────────────────────────────────
  // VALLE DEL CAUCA (76) — 42 municipios
  // ──────────────────────────────────────────────────────────────────────────
  { divipola: "76001", nombre: "Cali",                    depto: "Valle del Cauca", codigo_depto: "76" },
  { divipola: "76020", nombre: "Alcalá",                  depto: "Valle del Cauca", codigo_depto: "76" },
  { divipola: "76036", nombre: "Andalucía",               depto: "Valle del Cauca", codigo_depto: "76" },
  { divipola: "76041", nombre: "Ansermanuevo",            depto: "Valle del Cauca", codigo_depto: "76" },
  { divipola: "76054", nombre: "Argelia",                 depto: "Valle del Cauca", codigo_depto: "76" },
  { divipola: "76100", nombre: "Bolívar",                 depto: "Valle del Cauca", codigo_depto: "76" },
  { divipola: "76109", nombre: "Buenaventura",            depto: "Valle del Cauca", codigo_depto: "76" },
  { divipola: "76111", nombre: "Guadalajara de Buga",     depto: "Valle del Cauca", codigo_depto: "76" },
  { divipola: "76113", nombre: "Bugalagrande",            depto: "Valle del Cauca", codigo_depto: "76" },
  { divipola: "76122", nombre: "Caicedonia",              depto: "Valle del Cauca", codigo_depto: "76" },
  { divipola: "76126", nombre: "Calima",                  depto: "Valle del Cauca", codigo_depto: "76" },
  { divipola: "76130", nombre: "Candelaria",              depto: "Valle del Cauca", codigo_depto: "76" },
  { divipola: "76147", nombre: "Cartago",                 depto: "Valle del Cauca", codigo_depto: "76" },
  { divipola: "76233", nombre: "Dagua",                   depto: "Valle del Cauca", codigo_depto: "76" },
  { divipola: "76243", nombre: "El Águila",               depto: "Valle del Cauca", codigo_depto: "76" },
  { divipola: "76246", nombre: "El Cairo",                depto: "Valle del Cauca", codigo_depto: "76" },
  { divipola: "76248", nombre: "El Cerrito",              depto: "Valle del Cauca", codigo_depto: "76" },
  { divipola: "76250", nombre: "El Dovio",                depto: "Valle del Cauca", codigo_depto: "76" },
  { divipola: "76275", nombre: "Florida",                 depto: "Valle del Cauca", codigo_depto: "76" },
  { divipola: "76306", nombre: "Ginebra",                 depto: "Valle del Cauca", codigo_depto: "76" },
  { divipola: "76318", nombre: "Guacarí",                 depto: "Valle del Cauca", codigo_depto: "76" },
  { divipola: "76364", nombre: "Jamundí",                 depto: "Valle del Cauca", codigo_depto: "76" },
  { divipola: "76377", nombre: "La Cumbre",               depto: "Valle del Cauca", codigo_depto: "76" },
  { divipola: "76400", nombre: "La Unión",                depto: "Valle del Cauca", codigo_depto: "76" },
  { divipola: "76403", nombre: "La Victoria",             depto: "Valle del Cauca", codigo_depto: "76" },
  { divipola: "76497", nombre: "Obando",                  depto: "Valle del Cauca", codigo_depto: "76" },
  { divipola: "76520", nombre: "Palmira",                 depto: "Valle del Cauca", codigo_depto: "76" },
  { divipola: "76563", nombre: "Pradera",                 depto: "Valle del Cauca", codigo_depto: "76" },
  { divipola: "76606", nombre: "Restrepo",                depto: "Valle del Cauca", codigo_depto: "76" },
  { divipola: "76616", nombre: "Riofrío",                 depto: "Valle del Cauca", codigo_depto: "76" },
  { divipola: "76622", nombre: "Roldanillo",              depto: "Valle del Cauca", codigo_depto: "76" },
  { divipola: "76670", nombre: "San Pedro",               depto: "Valle del Cauca", codigo_depto: "76" },
  { divipola: "76736", nombre: "Sevilla",                 depto: "Valle del Cauca", codigo_depto: "76" },
  { divipola: "76823", nombre: "Toro",                    depto: "Valle del Cauca", codigo_depto: "76" },
  { divipola: "76828", nombre: "Trujillo",                depto: "Valle del Cauca", codigo_depto: "76" },
  { divipola: "76834", nombre: "Tuluá",                   depto: "Valle del Cauca", codigo_depto: "76" },
  { divipola: "76845", nombre: "Ulloa",                   depto: "Valle del Cauca", codigo_depto: "76" },
  { divipola: "76863", nombre: "Versalles",               depto: "Valle del Cauca", codigo_depto: "76" },
  { divipola: "76869", nombre: "Vijes",                   depto: "Valle del Cauca", codigo_depto: "76" },
  { divipola: "76890", nombre: "Yotoco",                  depto: "Valle del Cauca", codigo_depto: "76" },
  { divipola: "76892", nombre: "Yumbo",                   depto: "Valle del Cauca", codigo_depto: "76" },
  { divipola: "76895", nombre: "Zarzal",                  depto: "Valle del Cauca", codigo_depto: "76" },
];

// Eliminar duplicados por divipola (defensa ante el duplicado de Riosucio)
const seen = new Set<string>();
export const DIVIPOLA_PACIFICO_UNIQUE = DIVIPOLA_PACIFICO.filter((m) => {
  if (seen.has(m.divipola)) return false;
  seen.add(m.divipola);
  return true;
});
